### ISSUE TITLE
Hierarchical refinement

### ISSUE THREAD

**Issue by OVGULIU** [c-f-h/pyiga#1]
Hello!

can we also find a Hierarchical Refinement example based on PYIGA?

Thanks in advance!

**Comment by c-f-h** [comment]
Hi,

This is currently work in progress. We plan to publish such an example in the near future (say, a few weeks).

**Comment by c-f-h** [comment]
We now have a fully featured adaptive refinement example:

https://github.com/c-f-h/pyiga/blob/master/notebooks/adaptive.ipynb

**Comment by OVGULIU** [comment]
@c-f-h thanks!
