### ISSUE TITLE
Trouble Installing PyIGA

### ISSUE THREAD

**Issue by saikiabedanta** [c-f-h/pyiga#11]
Hello,

I'm having trouble installing PyIGA package. I'm doing **pip install PyIGA** , its showing "failed building wheel for PyIGA, so installed with setup.py".
When I do pip list pyiga is showing, but i cannot import it from my jupyter notebook.

I'm an amateur in all this, Can someone please help?

**Comment by c-f-h** [comment]
Hi,

pyiga cannot currently be installed with pip. (There is a different package with the same name on PyPI, but it is not this one and we don't maintain it.)

Please follow the instructions here to install it: https://github.com/c-f-h/pyiga#installation
You need to download the repository and execute `python setup.py install` manually.

I hope that helps!
