### ISSUE TITLE
geomdl " pre-processing" 

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [c-f-h/pyiga#2]
Hello!

Is it possible that  **geomdl** can be used for the pre (post)-processing of **pyiga**?

Best regards!

**Comment by c-f-h** [comment]
Hello,

For some reason I missed this issue until now, I'm sorry.

Thank you for pointing geomdl out, I was not aware of it. It seems useful. I think it would be quite easy to convert their B-spline/NURBS volume objects into pyiga's BSplineFunc/NurbsFunc classes. One would only need to extract the knot vectors and control points. Of course, advanced features like trimming are not currently supported in pyiga.
